### ISSUE TITLE
Fullscreen CSS tweak

### ISSUE THREAD

**Issue by richchurcher** [NiklasEi/bevy_game_template#102]
Thanks so much for maintaining this template, I really appreciate it especially the out-of-the-box CI/CD.

I notice that in order to get Itch.io full-screen working correctly (i.e. actually full-screen and not letterboxed) I'm needing to add the following CSS:

```css
canvas#bevy {
    flex-grow: 1;
    z-index: 2;
    height: 100% !important;
    width: 100% !important;
}
```
Perhaps a trifle hacky, but it does work. I think it may be something to do with the various styles Itch itself injects. Would you accept a PR like this, or is it something you'd prefer folks add after the fact?

Edit: I also needed to add
```css
    height: 100%;
    width: 100%;
```
to `.game-container`.
