### ISSUE TITLE
3d apps do not work in iOS simulator

### ISSUE THREAD

**Issue by rparrett** [NiklasEi/bevy_game_template#118]
3d scene with this template currently fail at runtime with the following shader error:

```2024-07-25T23:11:17.906190Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: naga_oil bug, please file a report: composer failed to build a valid header: Type [18] '' is invalid
 = Capability Capabilities(CUBE_ARRAY_TEXTURES) is required
```

After https://github.com/bevyengine/bevy/pull/12052, we have to do something like

```toml
[target.aarch64-apple-ios-sim.dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "ios_simulator",
] }
```

in `mobile/Cargo.toml`.
