### ISSUE TITLE
GitHub pages support

### ISSUE THREAD

**Issue by XBagon** [NiklasEi/bevy_game_template#23]
Are you interested in supporting GitHub pages for WASM builds?
I wanted to make my game's releases very easy to play.
For the moment I just added 
```yaml
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: wasm
          clean-exclude: index.html
```
as an additional step of  the release-wasm job.

In the future extending this feature to support multiple (all available) release and not just the most recent on could be very interesting.
