### ISSUE TITLE
Canvas not used with trunk?

### ISSUE THREAD

**Issue by sluedecke** [NiklasEi/bevy_game_template#76]
Thank you for this awesome template!  I migrated my [toy bevy game project](https://currit.net/theworld/) to it and it is just great to have all the deployment targets set up!

I notice that `trunk` adds a `canvas` element to `index.html` and does not use `<canvas id="bevy">`.

```shell
$ trunk --version
trunk 0.17.5
$ wasm-bindgen --version
wasm-bindgen 0.2.87
$ cargo --version
cargo 1.72.0 (103a7ff2e 2023-08-15)
```

I worked myself around it by removing this canvas element as well as the surrounding `div` container.

**Comment by NiklasEi** [comment]
Do I understand correctly that there were two `canvas` elements for you? Running `trunk build` in the root of the template creates a build in `dist` including an `index.html` with a single `canvas` element for me. I tested with trunk `0.16.0` and the latest `0.17.5`.

The `div` is in the template as a starting point for styling and custom pages to embed the canvas in.

**Comment by sluedecke** [comment]
It was my fault - I simply copied everything except the `src` where I have put my existing code.  I missed to add these lines to the setup of the `WindowPlugin`:

```rust
                    resolution: (800., 600.).into(),
                    // Bind to canvas included in `index.html`
                    canvas: Some("#bevy".to_owned()),
```

now it works as expected.  If I ommit the `canvas` directive, a new canvas object is inserted when calling `trunk serve`.

**Comment by sluedecke** [comment]
The resolution is specified twice, both in the `styles.css` and in the `resolution` setting for the `WindowPlugin`, so they have to be kept in sync.  If I use `fit_canvas_to_parent: true` instead of `resolution` and change the `styles.css` to this:

```css
body, html {
    height: 100%;
}

body {
    background: repeating-linear-gradient(
        135deg,
        #8b0000 0,
        #8b0000 2px,
        white 2px,
        white 20px
    );
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
}

.game-container {
    width: 800px;
    height: 600px;
}

#bevy {
    background-color: white;
}
```
I have the same effect, but specify the size only in the `.css` file.

**Comment by sluedecke** [comment]
The resolution is specified twice, both in the `styles.css` and in the `resolution` setting for the `WindowPlugin`, so they have to be kept in sync.  If I use `fit_canvas_to_parent: true` instead of `resolution` and change the `styles.css` to this:

```css
body, html {
    height: 100%;
}

body {
    background: repeating-linear-gradient(
        135deg,
        #8b0000 0,
        #8b0000 2px,
        white 2px,
        white 20px
    );
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
}

.game-container {
    width: 800px;
    height: 600px;
}

#bevy {
    background-color: white;
}
```
I have the same effect, but specify the size only in the `.css` file.
